#!/usr/bin/env bash
# DevNote: This script is kinda hard to re-write in a compiled language due to
# the way how a spawned process vs shell script modifies its environment. Using
# other forms of configs like yaml won't have the flexibility a shell script +
# source conf offers.

# -----------------------------[ CONFIGURATION ]----------------------------- #

# Default: project dir name
PROJECT_NAME=""
# Default: automatic detection
# Available values:
# none | rust | python | django | fastapi | flask | html | nodejs | nextjs | elixir | angular | flutter
PROJECT_TYPE=""

# Services: add any valid systemd services here
ENABLED_SERVICES=(
    # postgresql
    # docker
    # mongod
    # nginx
)

# Default: automatic detection
# Available values: none | {custom url}
URL=""
# Default: xdg-open
# Available values: {custom command with arguments ending with newtab flag}
BROWSER=""

# Settings: [ true | false ]
AUTORUN_COMMANDS=true

# ---------------------------[ CUSTOM OVERRIDES ]--------------------------- #

red='\033[1;31m'
cyan='\033[1;36m'
rst='\033[0;0m'

USE_CUSTOM_LAYOUT=false
setup_layout_custom() {
    log "🔴 Error: ${red}setup_layout_custom()${rst} not defined after ${cyan}USE_CUSTOM_LAYOUT=true${rst}"
}

USE_CUSTOM_ENV=false
setup_env_custom() {
    log "🔴 Error: ${red}setup_env_custom()${rst} not defined after ${cyan}USE_CUSTOM_ENV=true${rst}"
}

USE_POST_INITIALIZATION_HOOK=false
setup_post_init_hook() {
    log "🔴 Error: ${red}setup_post_init_hook()${rst} not defined after ${cyan}USE_POST_INITIALIZATION_HOOK=true${rst}"
}

# =========================================================================== #

# █░█ ▀█▀ █ █░░ █▀
# █▄█ ░█░ █ █▄▄ ▄█

# log(str:message)
log() {
    local green='\033[1;32m'
    local reset='\033[0;0m'
    echo -e "[${green}$(date +'%H:%M:%S')${reset}] $1"
}

# open_browser(str:new_tab_url str:browser_cmd?)
open_browser() {
    # CHECK: Valid URL
    local url="$1"
    if [[ -z "$url" ]]; then
        return
    fi

    # CHECK: Valid browser
    local browser="$2"
    if [[ -z "$browser" ]]; then
        browser="xdg-open"
    else
        command -v "${browser%% *}" >/dev/null || {
            log "❌ Error: ${browser%% *} not found"
            exit 1
        }
    fi

    log "🔗 Launching browser..."
    (
        # Wait for the server to start
        local timeout=20
        while ! curl -sf "$url" >/dev/null; do
            sleep 1
            ((timeout--)) || { exit 1; }
        done

        # Launch the browser
        $browser "$url" >/dev/null &
    ) &
}

ensure_window() {
    local name="$1"
    if tmux has-session -t "$PROJECT_NAME" 2>/dev/null; then
        tmux new-window -t "$PROJECT_NAME" -n "$name"
    else
        tmux new-session -d -s "$PROJECT_NAME" -n "$name"
    fi
}

# create_window(window_name:str command?:str)
create_window() {
    local name="$1"
    local cmd="$2"

    # CHECK: Valid Name
    if [[ -z "$name" ]]; then
        log "🚫 Error: Missing window name"
        return
    fi

    # ACTION: Window without command
    if [[ -z "$cmd" ]]; then
        ensure_window "$name"
        return
    fi

    # ACTION: Create window only if valid command
    if command -v "${cmd%% *}" >/dev/null; then
        ensure_window "$name"
        # "clear" Enter fixes send-keys doubling text due to shell race condition
        tmux send-keys -t "$PROJECT_NAME:$name" "clear" Enter "$cmd"
        if [ "$AUTORUN_COMMANDS" == true ]; then
            tmux send-keys -t "$PROJECT_NAME:$name" Enter
        fi
    fi
}

# create_temp_window(str:window_name str:command)
create_temp_window() {
    local name="$1"
    local cmd="$2"
    if command -v "${cmd%% *}" >/dev/null; then
        tmux new-window -t "$PROJECT_NAME" -n "$name" "$cmd"
    fi
}

# █▄▄ █▀█ █▀█ █░█░█ █▀ █▀▀ █▀█
# █▄█ █▀▄ █▄█ ▀▄▀▄▀ ▄█ ██▄ █▀▄

get_server_url() {
    local project_type="$1"
    case "$project_type" in
        "none") ;; # Do nothing
        "python") ;;
        "fastapi") ;;
        "flask") echo "http://localhost:5000" ;;
        "html")
            if command -v live-server >/dev/null; then
                echo "http://localhost:8080"
            fi
            ;;
        "django") echo "http://localhost:8000" ;;
        "nodejs") ;;
        "nextjs") echo "http://localhost:3000" ;;
        "angular") echo "http://localhost:4200" ;;
        "flutter") ;;
        "elixir") echo "http://localhost:4000" ;;
        "rust") ;;
        *) log "🚧 Warning: No server url for ${project_type}" ;;
    esac
}

# █░░ ▄▀█ █▄█ █▀█ █░█ ▀█▀ █▀
# █▄▄ █▀█ ░█░ █▄█ █▄█ ░█░ ▄█

# run_server_command(str:project_type)
run_server_command() {
    local project_type="$1"
    case "$project_type" in
        "none") ;; # Do nothing
        "python") echo "python main.py" ;;
        "fastapi") echo "uvicorn main:app --reload" ;;
        "flask") echo "python main.py" ;;
        "html")
            if command -v live-server >/dev/null; then
                echo "live-server --no-browser"
            fi
            ;;
        "django") echo "python manage.py runserver" ;;
        "nodejs") echo "npm start" ;;
        "nextjs") echo "npm run dev" ;;
        "angular") echo "ng serve" ;;
        "flutter") echo "flutter run" ;;
        "elixir") echo "iex -S mix phx.server" ;;
        "rust") echo "cargo run" ;;
        *) log "🚧 Warning: No server setup for ${project_type}" ;;
    esac
}

setup_base_layout() {
    create_window "Cmd" "$(run_server_command "$PROJECT_TYPE")"
    create_window "Editor" "nvim"
}

setup_fastapi_layout() {
    setup_base_layout
    create_window "Test" "clear && pytest"
}

setup_django_layout() {
    setup_base_layout
    create_window "Test" "python manage.py test"
}

setup_rust_layout() {
    setup_base_layout
    create_window "Test" "cargo test"
}

# select_layout(str:project_type)
setup_layout() {
    local project_type="$1"
    case "$project_type" in
        "none") setup_base_layout ;;
        "python") setup_base_layout ;;
        "django") setup_django_layout ;;
        "fastapi") setup_fastapi_layout ;;
        "flask") setup_base_layout ;;
        "html") setup_base_layout ;;
        "nodejs") setup_base_layout ;;
        "nextjs") setup_base_layout ;;
        "angular") setup_base_layout ;;
        "flutter") setup_base_layout ;;
        "elixir") setup_base_layout ;;
        "rust") setup_rust_layout ;;
        *)
            log "🚧 Unknown technology: ${project_type}. Using default layout..."
            setup_base_layout
            ;;
    esac
}

# █▀ █▀▀ █▀█ █░█ █ █▀▀ █▀▀ █▀
# ▄█ ██▄ █▀▄ ▀▄▀ █ █▄▄ ██▄ ▄█

init_services() {
    for service in "${ENABLED_SERVICES[@]}"; do
        if ! systemctl is-active --quiet "$service"; then
            log "🔧 Starting $service..."
            sudo systemctl start "$service"
        fi
    done
}

# █▀▀ █▄░█ █░█   █▀ █▀▀ ▀█▀ █░█ █▀█
# ██▄ █░▀█ ▀▄▀   ▄█ ██▄ ░█░ █▄█ █▀▀

# setup_base_env(str:dependency_dir str:dependency_cmd)
setup_base_env() {
    local dependency_dir="$1"
    local dependency_cmd="$2"
    if [[ ! -d $dependency_dir ]]; then
        log "🚀 Setting up dependencies..."
        command -v "${dependency_cmd%% *}" >/dev/null || {
            log "❌ Error: ${dependency_cmd%% *} not found"
            exit 1
        }
        $dependency_cmd
    fi
}

setup_python_env() {
    local dependency_dir="venv/"
    local dependency_cmd="python -m venv venv"
    if [[ ! -d $dependency_dir ]]; then
        setup_base_env "$dependency_dir" "$dependency_cmd"
        log "📦 Installing requirements..."
        # shellcheck disable=SC1090
        source "./$dependency_dir/bin/activate"
        if [[ -f "requirements.txt" ]]; then
            pip install -r requirements.txt
        else
            log "🚧 Warning: No requirements.txt found"
        fi
    else
        # shellcheck disable=SC1090
        source "./$dependency_dir/bin/activate"
    fi
}

setup_django_env() {
    setup_python_env
    # Run migrations if needed
    if python manage.py showmigrations --plan | grep '\[ \]'; then
        log "✈️ Running migrations to database..."
        python manage.py migrate
    fi
}

migrate_alembic() {
    # CHECK: alembic is installed
    if ! command -v alembic >/dev/null; then
        log "❌ Error: alembic.ini found but alembic is not installed"
        return
    fi

    log "🔍 Detected: alembic"
    # Capture both stdout + stderr
    local check_output
    check_output="$(alembic check 2>&1)"
    local check_status=$?

    if [[ $check_status == 0 ]]; then
        # CASE: Revision Created | DB Migrated
        log "✅ Alembic revision exists and DB is up to date"
        return
    fi

    case "$check_output" in
        *"ERROR [alembic.util.messaging] New upgrade operations detected"*)
            # CASE: Model Changed | Revision Not Created
            log "⚠️ Schema changes detected but no revision exists"

            case "$check_output" in
                *"INFO  [alembic.autogenerate.compare] Detected added table"*)
                    table_name=$(grep -oP "Detected added table '\K[^']+" <<<"$check_output")
                    log "💡 Hint: New tables detected. You probably want:"
                    log "   alembic revision --autogenerate -m \"add $table_name\""
                    log "   alembic upgrade head"
                    read -r -p "Press enter to continue"
                    ;;
                *)
                    log "💡 Hint: Model changes detected. Consider:"
                    log "   alembic revision --autogenerate -m \"schema changes\""
                    log "   alembic upgrade head"
                    read -r -p "Press enter to continue"
                    ;;
            esac

            return 1
            ;;

        *"ERROR [alembic.util.messaging] Target database is not up to date."*)
            # CASE: Revision Created | DB Not Migrated
            log "⚠️  Alembic revision exists but DB is not migrated"
            alembic upgrade head
            ;;

        *)
            # CASE: Unrecognized Error
            log "❌ Alembic failed with an unrecognized error"
            return 1
            ;;
    esac
}

setup_fastapi_env() {
    setup_python_env
    if [[ -f "alembic.ini" ]]; then
        migrate_alembic
    fi
}

setup_node_env() {
    setup_base_env "node_modules/" "npm install"
}

setup_elixir_env() {
    setup_base_env "deps/" "mix setup"
}

# select_env(str:project_type)
setup_env() {
    local project_type="$1"
    case "$project_type" in
        "none") ;; # Do nothing
        "python") setup_python_env ;;
        "django") setup_django_env ;;
        "fastapi") setup_fastapi_env ;;
        "flask") setup_python_env ;;
        "html") ;;
        "nodejs") setup_node_env ;;
        "nextjs") setup_node_env ;;
        "angular") setup_node_env ;;
        "flutter") ;;
        "elixir") setup_elixir_env ;;
        "rust") ;; # Rust sets up its own environment with cargo
        *) log "🚧 Unknown technology: ${project_type}" ;;
    esac
}

# █▀▄ █▀▀ ▀█▀ █▀▀ █▀▀ ▀█▀ █ █▀█ █▄░█
# █▄▀ ██▄ ░█░ ██▄ █▄▄ ░█░ █ █▄█ █░▀█

detect_project_type() {
    # python
    if [[ -f "main.py" ]]; then
        if grep -q "from fastapi import FastAPI" main.py; then
            echo "fastapi" && return
        elif grep -q "from flask import Flask" main.py; then
            echo "flask" && return
        fi
        echo "python" && return
    fi

    # django
    if [[ -f "manage.py" ]]; then
        echo "django" && return
    fi

    # nodejs
    if [[ -f "package.json" ]]; then
        if [[ -f "angular.json" ]]; then
            echo "angular" && return
        elif [[ -f "next.config.js" ]] || [[ -f "next.config.ts" ]] || [[ -f "next.config.mjs" ]]; then
            echo "nextjs" && return
        fi
        echo "nodejs" && return
    fi

    # flutter
    if [[ -f "pubspec.yaml" ]]; then
        echo "flutter" && return
    fi

    # elixir
    if [[ -f "mix.exs" ]]; then
        echo "elixir" && return
    fi

    # rust
    if [[ -f "Cargo.toml" ]]; then
        echo "rust" && return
    fi

    # html
    if [[ -f "index.html" ]]; then
        echo "html" && return
    fi

    # none
    echo "none" && return
}

# █▀▄▀█ ▄▀█ █ █▄░█
# █░▀░█ █▀█ █ █░▀█

main() {
    # INIT: Load global config if available
    config_file="$XDG_CONFIG_HOME/run/config.conf"
    # shellcheck disable=SC1090
    [[ -f "$config_file" ]] && source "$config_file"

    # INIT: Load custom overrides if available
    OVERRIDE_FILE=".runrc"
    # shellcheck disable=SC1090
    [[ -f "$OVERRIDE_FILE" ]] && source "$OVERRIDE_FILE"

    init_services

    # FALLBACK: PROJECT_NAME={project dir name}
    if [[ -z "$PROJECT_NAME" ]]; then
        PROJECT_NAME="$(basename "$PWD")"
        # Remove invalid characters
        PROJECT_NAME="${PROJECT_NAME//[^a-zA-Z0-9 -]/}"
        # EDGE_CASE: No valid characters at all
        if [[ -z "$PROJECT_NAME" ]]; then
            PROJECT_NAME="Invalid Project Name"
        fi
    fi

    # FALLBACK: PROJECT_TYPE={automatic detection}
    if [[ -z "$PROJECT_TYPE" ]]; then
        PROJECT_TYPE="$(detect_project_type)"
        log "🔍 Detected: $PROJECT_TYPE"
    fi

    # FALLBACK: NEW_TAB_URL={automatic detection}
    if [[ -z "$URL" ]]; then
        URL=$(get_server_url "$PROJECT_TYPE")
    fi

    # SETUP: ENV or custom
    if [[ "$USE_CUSTOM_ENV" = true ]]; then
        setup_env_custom
    else
        setup_env "$PROJECT_TYPE"
    fi

    # ACTION: OPEN BROWSER
    if [[ "$URL" != "none" ]]; then
        open_browser "$URL" "$BROWSER"
    fi

    # REQUIRE: tmux dependency for LAYOUT
    if ! command -v tmux >/dev/null; then
        # FALLBACK: RUN SERVER (Blocking)
        cmd=$(run_server_command "$PROJECT_TYPE")
        if [[ -z "$cmd" ]]; then
            log "🚫 Error: No server found for this type"
            exit 1
        fi
        log "ℹ️ Running server without tmux..."
        eval "$cmd"
        exit 0
    fi

    # ACTION: Attach session if exists
    if tmux has-session -t "$PROJECT_NAME" 2>/dev/null; then
        log "Session '$PROJECT_NAME' already exists. Attaching..."
        tmux attach -t "$PROJECT_NAME"
        exit 0
    fi

    # SETUP: LAYOUT or custom
    if [[ "$USE_CUSTOM_LAYOUT" = true ]]; then
        setup_layout_custom
    else
        setup_layout "$PROJECT_TYPE"
    fi

    # ACTION: POST INIT HOOK
    if [[ "$USE_POST_INITIALIZATION_HOOK" = true ]]; then
        setup_post_init_hook
    fi

    tmux attach -t "$PROJECT_NAME"
}

main

log "👋 Goodbye!"
